# Generated by Django 4.2.7 on 2023-11-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0002_registrationformpage_event_enable_registration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Registration'},
        ),
        migrations.AddField(
            model_name='event',
            name='enable_email',
            field=models.BooleanField(default=False),
        ),
    ]
